newPRWelcomeComment: >
  Thank you 🎉 for opening this pull request!💖
  Please make sure you have followed our [Contributing Guidelines](https://github.com/Saikat-98/World-Covid-Tracker/blob/main/CONTRIBUTING.md).🙌
  We will test out your code and reply in a bit with some pointers and requests.💿
  There may be some errors, **but don't worry!** We'll work through them with you! 👍🎉😄
  

firstPRMergeComment: >
  Congrats on merging your first pull request! 🙌🎉⚡️
  Now that you've merged your first pull request, you're the perfect person to help someone else out with this challenging first step.😄🙌


newIssueWelcomeComment: >
  Hello there!👋 Welcome to the project!🚀⚡
  Thank you and congrats🎉 for opening your very first issue in this project. Please adhere to our [Code of Conduct](https://github.com/Saikat-98/World-Covid-Tracker/blob/main/Code_Of_Conduct.md).🙌
  If you have screenshots or a gif to share demonstrating the issue, that's really helpful!📸
  Please make sure not to start working on the issue, unless you get assigned to it.😄
   